import time
import random

random.seed(time.time())

fortunes = [
    '\nYou love your home and want it to be beautiful.\n',
    '\nIt usually takes more than three weeks to prepare a good impromptu speech.\n        -- Mark Twain\n',
    '\nQ:Why does Washington have the most lawyers per capita and\n    New Jersey the most toxic waste dumps?\nA:God gave New Jersey first choice.\n',
    '\nMake a wish, it might come true.\n',
    "\nGood night to spend with family, but avoid arguments with your mate's\nnew lover.\n",
    '\nYou get along very well with everyone except animals and people.\n',
    '\nI must have a prodigious quantity of mind; it takes me as much as a\nweek sometimes to make it up.\n        -- Mark Twain, "The Innocents Abroad"\n',
    '\nBeauty and harmony are as necessary to you as the very breath of life.\n',
    '\nThe last thing one knows in constructing a work is what to put first.\n        -- Blaise Pascal\n',
    '\nYour temporary financial embarrassment will be relieved in a surprising manner.\n',
    "\nQ:How many lawyers does it take to change a light bulb?\nA:One.  Only it's his light bulb when he's done.\n",
    '\nAbandon the search for Truth; settle for a good fantasy.\n',
    '\nYou will be advanced socially, without any special effort on your part.\n',
    '\nYou are going to have a new love affair.\n',
    '\nGive thought to your reputation.  Consider changing name and moving to\na new town.\n',
    '\nExcellent day to have a rotten day.\n',
    '\nYou will be honored for contributing your time and skill to a worthy cause.\n',
    "\nQ:What's the difference between a Mac and an Etch-a-Sketch?\nA:You don't have to shake the Mac to clear the screen.\n",
    '\nSo she went into the garden to cut a cabbage leaf to make an apple pie;\nand at the same time a great she-bear, coming up the street pops its head\ninto the shop. "What! no soap?" So he died, and she very imprudently\nmarried the barber; and there were present the Picninnies, and the Grand\nPanjandrum himself, with the little round button at top, and they all\nfell to playing the game of catch as catch can, till the gunpowder ran\nout at the heels of their boots.\n        -- Samuel Foote\n',
    '\nTry the Moo Shu Pork.  It is especially good today.\n',
    "\nQ:How many IBM 370's does it take to execute a job?\nA:Four, three to hold it down, and one to rip its head off.\n",
    '\nYou have a strong desire for a home and your family interests come first.\n',
    '\nOctober 12, the Discovery.\n\nIt was wonderful to find America, but it would have been more wonderful to miss\nit.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nFine day for friends.\nSo-so day for you.\n',
    '\nHow apt the poor are to be proud.\n        -- William Shakespeare, "Twelfth-Night"\n',
    '\nAll the troubles you have will pass away very quickly.\n',
    '\nYou will gain money by an immoral action.\n',
    '\nThe Least Perceptive Literary Critic\n    The most important critic in our field of study is Lord Halifax.  A\nmost individual judge of poetry, he once invited Alexander Pope round to\ngive a public reading of his latest poem.\n    Pope, the leading poet of his day, was greatly surprised when Lord\nHalifax stopped him four or five times and said, "I beg your pardon, Mr.\nPope, but there is something in that passage that does not quite please me."\n    Pope was rendered speechless, as this fine critic suggested sizeable\nand unwise emendations to his latest masterpiece.  "Be so good as to mark\nthe place and consider at your leisure.  I\'m sure you can give it a better\nturn."\n    After the reading, a good friend of Lord Halifax, a certain Dr.\nGarth, took the stunned Pope to one side.  "There is no need to touch the\nlines," he said.  "All you need do is leave them just as they are, call on\nLord Halifax two or three months hence, thank him for his kind observation\non those passages, and then read them to him as altered.  I have known him\nmuch longer than you have, and will be answerable for the event."\n    Pope took his advice, called on Lord Halifax and read the poem\nexactly as it was before.  His unique critical faculties had lost none of\ntheir edge.  "Ay", he commented, "now they are perfectly right.  Nothing can\nbe better."\n        -- Stephen Pile, "The Book of Heroic Failures"\n',
    '\nYou teach best what you most need to learn.\n',
    '\nYou will be surprised by a loud noise.\n',
    '\nYou are farsighted, a good planner, an ardent lover, and a faithful friend.\n',
    "\nFortune: You will be attacked next Wednesday at 3:15 p.m. by six samurai\nsword wielding purple fish glued to Harley-Davidson motorcycles.\n\nOh, and have a nice day!\n        -- Bryce Nesbitt '84\n",
    '\nAlimony and bribes will engage a large share of your wealth.\n',
    '\nQ:How many Zen masters does it take to screw in a light bulb?\nA:None.  The Universe spins the bulb, and the Zen master stays out\n    of the way.\n',
    '\nFORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #15\nA:The Royal Canadian Mounted Police.\nQ:What was the greatest achievement in taxidermy?\n',
    '\nYou are scrupulously honest, frank, and straightforward.  Therefore you\nhave few friends.\n',
    "\nYou will become rich and famous unless you don't.\n",
    "\nThe countdown had stalled at 'T' minus 69 seconds when Desiree, the first\nfemale ape to go up in space, winked at me slyly and pouted her thick,\nrubbery lips unmistakably -- the first of many such advances during what\nwould prove to be the longest, and most memorable, space voyage of my\ncareer.\n        -- Winning sentence, 1985 Bulwer-Lytton bad fiction contest.\n",
    '\nYou possess a mind not merely twisted, but actually sprained.\n',
    '\nYour aims are high, and you are capable of much.\n',
    '\nYou have a deep interest in all that is artistic.\n',
    '\nAmong the lucky, you are the chosen one.\n',
    '\nYour step will soil many countries.\n',
    '\nYour mode of life will be changed for the better because of new developments.\n',
    "\nQ:What's tan and black and looks great on a lawyer?\nA:A doberman.\n",
    '\nThey spell it "da Vinci" and pronounce it "da Vinchy".  Foreigners\nalways spell better than they pronounce.\n        -- Mark Twain\n',
    '\nShips are safe in harbor, but they were never meant to stay there.\n',
    '\nDo what comes naturally.  Seethe and fume and throw a tantrum.\n',
    '\nYou can create your own opportunities this week.  Blackmail a senior executive.\n',
    "\nWagner's music is better than it sounds.\n        -- Mark Twain\n",
    '\nYour true value depends entirely on what you are compared with.\n',
    '\nKeep emotionally active.  Cater to your favorite neurosis.\n',
    '\nF.S. Fitzgerald to Hemingway:\n    "Ernest, the rich are different from us."\nHemingway:\n    "Yes.  They have more money."\n',
    '\n    "...The name of the song is called \'Haddocks\' Eyes\'!"\n    "Oh, that\'s the name of the song, is it?" Alice said, trying to\nfeel interested.\n    "No, you don\'t understand," the Knight said, looking a little\nvexed.  "That\'s what the name is called.  The name really is, \'The Aged\nAged Man.\'"\n    "Then I ought to have said "That\'s what the song is called\'?"\nAlice corrected herself.\n    "No, you oughtn\'t: that\'s quite another thing!  The song is\ncalled \'Ways and Means\':  but that\'s only what it is called you know!"\n    "Well, what is the song then?" said Alice, who was by this\ntime completely bewildered.\n    "I was coming to that," the Knight said.  "The song really is\n"A-sitting on a Gate": and the tune\'s my own invention."\n        -- Lewis Carroll, "Through the Looking Glass"\n',
    '\nA visit to a strange place will bring fresh work.\n',
    '\nQ:How many Oregonians does it take to screw in a light bulb?\nA:Three.  One to screw in the light bulb and two to fend off all those\n    Californians trying to share the experience.\n',
    '\nOne of the most striking differences between a cat and a lie is that a cat has\nonly nine lives.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nIt is often the case that the man who can\'t tell a lie thinks he is the best\njudge of one.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nWhoever has lived long enough to find out what life is, knows how deep a debt\nof gratitude we owe to Adam, the first great benefactor of our race.  He\nbrought death into the world.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nThings will be bright in P.M.  A cop will shine a light in your face.\n',
    '\nYou are always busy.\n',
    '\nTry to have as good a life as you can under the circumstances.\n',
    '\nYou are fairminded, just and loving.\n',
    "\nWhen one burns one's bridges, what a very nice fire it makes.\n        -- Dylan Thomas\n",
    '\nIn the plot, people came to the land; the land loved them; they worked and\nstruggled and had lots of children.  There was a Frenchman who talked funny\nand a greenhorn from England who was a fancy-pants but when it came to the\ncrunch he was all courage.  Those novels would make you retch.\n        -- Canadian novelist Robertson Davies, on the generic Canadian\n           novel.\n',
    '\nGreen light in A.M. for new projects.  Red light in P.M. for traffic tickets.\n',
    "\nQ:What's the difference between Bell Labs and the Boy Scouts of America?\nA:The Boy Scouts have adult supervision.\n",
    "\nDon't Worry, Be Happy.\n        -- Meher Baba\n",
    '\nQ:Why did the lone ranger kill Tonto?\nA:He found out what "kimosabe" really means.\n',
    '\nYour love life will be happy and harmonious.\n',
    '\nLife is to you a dashing and bold adventure.\n',
    '\nQ:What\'s the difference between the 1950\'s and the 1980\'s?\nA:In the 80\'s, a man walks into a drugstore and states loudly, "I\'d\n    like some condoms," and then, leaning over the counter, whispers,\n    "and some cigarettes."\n',
    '\nQ:Minnesotans ask, "Why aren\'t there more pharmacists from Alabama?"\nA:Easy.  It\'s because they can\'t figure out how to get the little\n    bottles into the typewriter.\n',
    '\nIt is easy to find fault, if one has that disposition.  There was once a man\nwho, not being able to find any other fault with his coal, complained that\nthere were too many prehistoric toads in it.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nYou love peace.\n',
    "\nYou'll never see all the places, or read all the books, but fortunately,\nthey're not all recommended.\n",
    '\nTempt not a desperate man.\n        -- William Shakespeare, "Romeo and Juliet"\n',
    '\nBe security conscious -- National defense is at stake.\n',
    '\nThere are three infallible ways of pleasing an author, and the three form a\nrising scale of compliment: 1, to tell him you have read one of his books; 2,\nto tell him you have read all of his books; 3, to ask him to let you read the\nmanuscript of his forthcoming book.  No. 1 admits you to his respect; No. 2\nadmits you to his admiration; No. 3 carries you clear into his heart.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nFine day to work off excess energy.  Steal something heavy.\n',
    '\nA tall, dark stranger will have more fun than you.\n',
    '\nYou will always get the greatest recognition for the job you least like.\n',
    '\nKiss me, Kate, we will be married o\' Sunday.\n        -- William Shakespeare, "The Taming of the Shrew"\n',
    "\nFORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #21\nA:Dr. Livingston I. Presume.\nQ:What's Dr. Presume's full name?\n",
    '\nYour business will go through a period of considerable expansion.\n',
    '\nHope that the day after you die is a nice day.\n',
    '\nQ:How many Martians does it take to screw in a light bulb?\nA:One and a half.\n',
    '\nIt has long been an axiom of mine that the little things are infinitely\nthe most important.\n        -- Sir Arthur Conan Doyle, "A Case of Identity"\n',
    '\nThe first thing we do, let\'s kill all the lawyers.\n        -- Wm. Shakespeare, "Henry VI", Part IV\n',
    '\nYou have an ambitious nature and may make a name for yourself.\n',
    '\nYou have an unusual equipment for success.  Be sure to use it properly.\n',
    "\nQ:How many elephants can you fit in a VW Bug?\nA:Four.  Two in the front, two in the back.\n\nQ:How can you tell if an elephant is in your refrigerator?\nA:There's a footprint in the mayo.\n\nQ:How can you tell if two elephants are in your refrigerator?\nA:There's two footprints in the mayo.\n\nQ:How can you tell if three elephants are in your refrigerator?\nA:The door won't shut.\n\nQ:How can you tell if four elephants are in your refrigerator?\nA:There's a VW Bug in your driveway.\n",
    "\nI was gratified to be able to answer promptly, and I did. I said I didn't know.\n        -- Mark Twain\n",
    "\nAnyone who has had a bull by the tail knows five or six more things\nthan someone who hasn't.\n        -- Mark Twain\n",
    '\nYou will attract cultured and artistic people to your home.\n',
    "\nDon't tell any big lies today.  Small ones can be just as effective.\n",
    '\nEven the clearest and most perfect circumstantial evidence is likely to be at\nfault, after all, and therefore ought to be received with great caution.  Take\nthe case of any pencil, sharpened by any woman; if you have witnesses, you will\nfind she did it with a knife; but if you take simply the aspect of the pencil,\nyou will say that she did it with her teeth.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nYou will live a long, healthy, happy life and make bags of money.\n',
    '\nQ:How many college football players does it take to screw in a light bulb?\nA:Only one, but he gets three credits for it.\n',
    "\nDon't you feel more like you do now than you did when you came in?\n",
    '\nYou will be married within a year, and divorced within two.\n',
    '\nAn avocado-tone refrigerator would look good on your resume.\n',
    '\nThey have been at a great feast of languages, and stolen the scraps.\n        -- William Shakespeare, "Love\'s Labour\'s Lost"\n',
    "\nThe bone-chilling scream split the warm summer night in two, the first\nhalf being before the scream when it was fairly balmy and calm and\npleasant, the second half still balmy and quite pleasant for those who\nhadn't heard the scream at all, but not calm or balmy or even very nice\nfor those who did hear the scream, discounting the little period of time\nduring the actual scream itself when your ears might have been hearing it\nbut your brain wasn't reacting yet to let you know.\n        -- Winning sentence, 1986 Bulwer-Lytton bad fiction contest.\n",
    '\nYour aim is high and to the right.\n',
    "\nFORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #5\nA:The Halls of Montezuma and the Shores of Tripoli.\nQ:Name two families whose kids won't join the Marines.\n",
    "\nYou're almost as happy as you think you are.\n",
    '\nYour nature demands love and your happiness depends on it.\n',
    '\n"Elves and Dragons!" I says to him.  "Cabbages and potatoes are better\nfor you and me."\n        -- J. R. R. Tolkien\n',
    '\nTroubled day for virgins over 16 who are beautiful and wealthy and live\nin eucalyptus trees.\n',
    '\nDomestic happiness and faithful friends.\n',
    "\nYour reasoning is excellent -- it's only your basic assumptions that are wrong.\n",
    '\nQ:How many WASPs does it take to change a light bulb?\nA:One.\n',
    '\nIf more of us valued food and cheer and song above hoarded gold, it would\nbe a merrier world.\n        -- J.R.R. Tolkien\n',
    '\nPatch griefs with proverbs.\n        -- William Shakespeare, "Much Ado About Nothing"\n',
    '\nYou never know how many friends you have until you rent a house on the beach.\n',
    "\nQ:How many IBM CPU's does it take to do a logical right shift?\nA:33.  1 to hold the bits and 32 to push the register.\n",
    '\nO, what a tangled web we weave, When first we practice to deceive.\n        -- Sir Walter Scott, "Marmion"\n',
    '\nYou may worry about your hair-do today, but tomorrow much peanut butter will\nbe sold.\n',
    '\nYou recoil from the crude; you tend naturally toward the exquisite.\n',
    '\nSteady movement is more important than speed, much of the time.  So long\nas there is a regular progression of stimuli to get your mental hooks\ninto, there is room for lateral movement.  Once this begins, its rate is\na matter of discretion.\n        -- Corwin, Prince of Amber\n',
    '\nYou will contract a rare disease.\n',
    '\nYou will hear good news from one you thought unfriendly to you.\n',
    '\nExcellent time to become a missing person.\n',
    "\nI've touch'd the highest point of all my greatness;\nAnd from that full meridian of my glory\nI haste now to my setting.  I shall fall,\nLike a bright exhalation in the evening\nAnd no man see me more.\n        -- Shakespeare\n",
    '\nYou like to form new friendships and make new acquaintances.\n',
    '\nA visit to a fresh place will bring strange work.\n',
    '\nSometimes I wonder if I\'m in my right mind.  Then it passes off and I\'m\nas intelligent as ever.\n        -- Samuel Beckett, "Endgame"\n',
    '\nYou own a dog, but you can only feed a cat.\n',
    '\nBeware of a dark-haired man with a loud tie.\n',
    "\nGive your very best today.  Heaven knows it's little enough.\n",
    '\nYou will experience a strong urge to do good; but it will pass.\n',
    '\nWhen I reflect upon the number of disagreeable people who I know who have gone\nto a better world, I am moved to lead a different life.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    "\nQ:How many lawyers does it take to change a light bulb?\nA:You won't find a lawyer who can change a light bulb.  Now, if\n    you're looking for a lawyer to screw a light bulb...\n",
    '\nQ:How much does it cost to ride the Unibus?\nA:2 bits.\n',
    '\nQ:How many bureaucrats does it take to screw in a light bulb?\nA:Two.  One to assure everyone that everything possible is being\n    done while the other screws the bulb into the water faucet.\n',
    '\nGood day for a change of scene.  Repaper the bedroom wall.\n',
    '\nA classic is something that everyone wants to have read\nand nobody wants to read.\n        -- Mark Twain, "The Disappearance of Literature"\n',
    '\nQ:How many supply-siders does it take to change a light bulb?\nA:None.  The darkness will cause the light bulb to change by itself.\n',
    '\nQ:How many lawyers does it take to change a light bulb?\nA:Whereas the party of the first part, also known as "Lawyer", and the\nparty of the second part, also known as "Light Bulb", do hereby and forthwith\nagree to a transaction wherein the party of the second part shall be removed\nfrom the current position as a result of failure to perform previously agreed\nupon duties, i.e., the lighting, elucidation, and otherwise illumination of\nthe area ranging from the front (north) door, through the entryway, terminating\nat an area just inside the primary living area, demarcated by the beginning of\nthe carpet, any spillover illumination being at the option of the party of the\nsecond part and not required by the aforementioned agreement between the\nparties.\n    The aforementioned removal transaction shall include, but not be\nlimited to, the following.  The party of the first part shall, with or without\nelevation at his option, by means of a chair, stepstool, ladder or any other\nmeans of elevation, grasp the party of the second part and rotate the party\nof the second part in a counter-clockwise direction, this point being tendered\nnon-negotiable.  Upon reaching a point where the party of the second part\nbecomes fully detached from the receptacle, the party of the first part shall\nhave the option of disposing of the party of the second part in a manner\nconsistent with all relevant and applicable local, state and federal statutes.\nOnce separation and disposal have been achieved, the party of the first part\nshall have the option of beginning installation.  Aforesaid installation shall\noccur in a manner consistent with the reverse of the procedures described in\nstep one of this self-same document, being careful to note that the rotation\nshould occur in a clockwise direction, this point also being non-negotiable.\nThe above described steps may be performed, at the option of the party of the\nfirst part, by any or all agents authorized by him, the objective being to\nproduce the most possible revenue for the Partnership.\n',
    '\nFor a light heart lives long.\n        -- Shakespeare, "Love\'s Labour\'s Lost"\n',
    "\nFORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #31\nA:Chicken Teriyaki.\nQ:What is the name of the world's oldest kamikaze pilot?\n",
    '\nYou will be successful in love.\n',
    "\nYour best consolation is the hope that the things you failed to get weren't\nreally worth having.\n",
    '\nA banker is a fellow who lends you his umbrella when the sun is shining\nand wants it back the minute it begins to rain.\n        -- Mark Twain\n',
    '\nYou will be the victim of a bizarre joke.\n',
    '\nSomeone is speaking well of you.\n\nHow unusual!\n',
    '\nYou worry too much about your job.  Stop it.  You are not paid enough to worry.\n',
    '\nYou will live to see your grandchildren.\n',
    '\nQ:Why do people who live near Niagara Falls have flat foreheads?\nA:Because every morning they wake up thinking "What *is* that noise?\n    Oh, right, *of course*!\n',
    '\nYour mode of life will be changed for the better because of good news soon.\n',
    '\nTry to relax and enjoy the crisis.\n        -- Ashleigh Brilliant\n',
    '\nLearn to pause -- or nothing worthwhile can catch up to you.\n',
    '\n"Good afternoon, madam.  How may I help you?"\n\n"Good afternoon.  I\'d like a FrintArms HandCannon, please."\n\n"A--?  Oh, now, that\'s an awfully big gun for such a lovely lady.  I\nmean, not everybody thinks ladies should carry guns at all, though I\nsay they have a right to.  But I think... I might... Let\'s have a look\ndown here.  I might have just the thing for you.  Yes, here we are!\nLook at that, isn\'t it neat?  Now that is a FrintArms product as well,\nbut it\'s what\'s called a laser -- a light-pistol some people call\nthem.  Very small, as you see; fits easily into a pocket or bag; won\'t\nspoil the line of a jacket; and you won\'t feel you\'re lugging half a\ntonne of iron around with you.  We do a range of matching accessories,\nincluding -- if I may say so -- a rather saucy garter holster.  Wish I\ngot to do the fitting for that!  Ha -- just my little joke.  And\nthere\'s *even*... here we are -- this special presentation pack: gun,\ncharged battery, charging unit, beautiful glider-hide shoulder holster\nwith adjustable fitting and contrast stitching, and a discount on your\nnext battery.  Full instructions, of course, and a voucher for free\nlessons at your local gun club or range.  Or there\'s the *special*\npresentation pack; it has all the other one\'s got but with *two*\ncharged batteries and a night-sight, too.  Here, feel that -- don\'t\nworry, it\'s a dummy battery -- isn\'t it neat?  Feel how light it is?\nSmooth, see?  No bits to stick out and catch on your clothes, *and*\nbeautifully balanced.  And of course the beauty of a laser is, there\'s\nno recoil.  Because it\'s shooting light, you see?  Beautiful gun,\nbeautiful gun; my wife has one.  Really.  That\'s not a line, she\nreally has.  Now, I can do you that one -- with a battery and a free\ncharge -- for ninety-five; or the presentation pack on a special\noffer for one-nineteen; or this, the special presentation pack, for\none-forty-nine."\n\n"I\'ll take the special."\n\n"Sound choice, madam, *sound* choice.  Now, do--?"\n\n"And a HandCannon, with the eighty-mill silencer, five GP clips, three\nsix-five AP/wire-flechettes clips, two bipropellant HE clips, and a\nSpecial Projectile Pack if you have one -- the one with the embedding\nrounds, not the signalers.  I assume the night-sight on this toy is\ncompatible?"\n\n"Aah... yes,  And how does madam wish to pay?"\n\nShe slapped her credit card on the counter.  "Eventually."\n\n        -- Iain M. Banks, "Against a Dark Background"\n',
    '\nA kind of Batman of contemporary letters.\n        -- Philip Larkin on Anthony Burgess\n',
    '\nFORTUNE PROVIDES QUESTIONS FOR THE GREAT ANSWERS: #4\nA:Go west, young man, go west!\nQ:What do wabbits do when they get tiwed of wunning awound?\n',
    '\nConsider well the proportions of things.  It is better to be a young June-bug\nthan an old bird of paradise.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nFew things are harder to put up with than the annoyance of a good example.\n        -- "Mark Twain, Pudd\'nhead Wilson\'s Calendar"\n',
    '\nHe draweth out the thread of his verbosity finer than the staple of his\nargument.\n        -- William Shakespeare, "Love\'s Labour\'s Lost"\n',
    '\nYou will be awarded some great honor.\n',
    "\nMany a writer seems to think he is never profound except when he can't\nunderstand his own meaning.\n        -- George D. Prentice\n",
    '\nWhat good is an obscenity trial except to popularize literature?\n        -- Nero Wolfe, "The League of Frightened Men"\n',
    "\nYou are a very redundant person, that's what kind of person you are.\n",
    '\nSo so is good, very good, very excellent good:\nand yet it is not; it is but so so.\n        -- William Shakespeare, "As You Like It"\n',
    "\nYou'll feel much better once you've given up hope.\n",
    "\nGone With The Wind LITE(tm)\n    -- by Margaret Mitchell\n\n    A woman only likes men she can't have and the South gets trashed.\n\nGift of the Magi LITE(tm)\n    -- by O. Henry\n\n    A husband and wife forget to register their gift preferences.\n\nThe Old Man and the Sea LITE(tm)\n    -- by Ernest Hemingway\n\n    An old man goes fishing, but doesn't have much luck.\n",
    '\nYou have many friends and very few living enemies.\n',
    '\nThere is no hunting like the hunting of man, and those who have hunted\narmed men long enough and liked it, never care for anything else thereafter.\n        -- Ernest Hemingway\n',
    '\nGood day for overcoming obstacles.  Try a steeplechase.\n',
    '\nIt may or may not be worthwhile, but it still has to be done.\n',
    '\nAn exotic journey in downtown Newark is in your future.\n',
    '\nI do desire we may be better strangers.\n        -- William Shakespeare, "As You Like It"\n',
    '\nYou have the body of a 19 year old.  Please return it before it gets wrinkled.\n',
    '\nQ:What do monsters eat?\nA:Things.\n\nQ:What do monsters drink?\nA:Coke.  (Because Things go better with Coke.)\n',
    '\nAvert misunderstanding by calm, poise, and balance.\n',
    '\nSwerve me?  The path to my fixed purpose is laid with iron rails,\nwhereon my soul is grooved to run.  Over unsounded gorges, through\nthe rifled hearts of mountains, under torrents\' beds, unerringly I rush!\n        -- Captain Ahab, "Moby Dick"\n',
    '\n"... an experienced, industrious, ambitious, and often quite often\npicturesque liar."\n        -- Mark Twain\n',
    '\nThe difference between the right word and the almost right word is the\ndifference between lightning and the lightning bug.\n        -- Mark Twain\n',
    '\nYour manuscript is both good and original, but the part that is good is not\noriginal and the part that is original is not good.\n        -- Samuel Johnson\n',
    '\nYou will be married within a year.\n',
    '\nYou need more time; and you probably always will.\n',
    "\nQ:How many Bell Labs Vice Presidents does it take to change a light bulb?\nA:That's proprietary information.  Answer available from AT&T on payment\n    of license fee (binary only).\n",
    '\nThere is no character, howsoever good and fine, but it can be destroyed by\nridicule, howsoever poor and witless.  Observe the ass, for instance: his\ncharacter is about perfect, he is the choicest spirit among all the humbler\nanimals, yet see what ridicule has brought him to.  Instead of feeling\ncomplimented when we are called an ass, we are left in doubt.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nQ:What is the sound of one cat napping?\nA:Mu.\n',
    '\nWhat I tell you three times is true.\n        -- Lewis Carroll\n',
    '\nA light wife doth make a heavy husband.\n        -- Wm. Shakespeare, "The Merchant of Venice"\n',
    '\nA long-forgotten loved one will appear soon.\n\nBuy the negatives at any price.\n',
    '\nAn honest tale speeds best being plainly told.\n        -- William Shakespeare, "Henry VI"\n',
    '\nYou see, I consider that a man\'s brain originally is like a little empty\nattic, and you have to stock it with such furniture as you choose.  A fool\ntakes in all the lumber of every sort he comes across, so that the knowledge\nwhich might be useful to him gets crowded out, or at best is jumbled up with\na lot of other things, so that he has difficulty in laying his hands upon it.\nNow the skilful workman is very careful indeed as to what he takes into his\nbrain-attic.  He will have nothing but the tools which may help him in doing\nhis work, but of these he has a large assortment, and all in the most perfect\norder.  It is a mistake to think that that little room has elastic walls and\ncan distend to any extent.  Depend upon it there comes a time when for every\naddition of knowledge you forget something that you knew before.  It is of\nthe highest importance, therefore, not to have useless facts elbowing out\nthe useful ones.\n        -- Sir Arthur Conan Doyle, "A Study in Scarlet"\n',
    '\nAnother good night not to sleep in a eucalyptus tree.\n',
    '\nYour present plans will be successful.\n',
    '\nYou will meet an important person who will help you advance professionally.\n',
    '\nNever look up when dragons fly overhead.\n',
    "\nQ:How many surrealists does it take to change a light bulb?\nA:Two, one to hold the giraffe, and the other to fill the bathtub\n    with brightly colored machine tools.\n\n    [Surrealist jokes just aren't my cup of fur.  Ed.]\n",
    '\nQ:What does a WASP Mom make for dinner?\nA:A crisp salad, a hearty soup, a lovely entree, followed by\n    a delicious dessert.\n',
    "\nBetter hope the life-inspector doesn't come around while you have your\nlife in such a mess.\n",
    '\n    "You have heard me speak of Professor Moriarty?"\n    "The famous scientific criminal, as famous among crooks as --"\n    "My blushes, Watson," Holmes murmured, in a deprecating voice.\n    "I was about to say \'as he is unknown to the public.\'"\n        -- A. Conan Doyle, "The Valley of Fear"\n',
    '\nIs that really YOU that is reading this?\n',
    '\nQ:Know what the difference between your latest project\n    and putting wings on an elephant is?\nA:Who knows?  The elephant *might* fly, heh, heh...\n',
    '\nThe ripest fruit falls first.\n        -- William Shakespeare, "Richard II"\n',
    '\nWhen you are about to die, a wombat is better than no company at all.\n        -- Roger Zelazny, "Doorways in the Sand"\n',
    '\nQ:How many existentialists does it take to screw in a light bulb?\nA:Two.  One to screw it in and one to observe how the light bulb\n    itself symbolizes a single incandescent beacon of subjective\n    reality in a netherworld of endless absurdity reaching out toward a\n    maudlin cosmos of nothingness.\n',
    "\nQ:How many DEC repairman does it take to fix a flat?\nA:Five; four to hold the car up and one to swap tires.\n\nQ:How long does it take?\nA:It's indeterminate.\n    It will depend upon how many flats they've brought with them.\n\nQ:What happens if you've got TWO flats?\nA:They replace your generator.\n",
    '\nNever reveal your best argument.\n',
    "\nDon't go around saying the world owes you a living.  The world owes you\nnothing.  It was here first.\n        -- Mark Twain\n",
    '\nThe fashion wears out more apparel than the man.\n        -- William Shakespeare, "Much Ado About Nothing"\n',
    '\nYou feel a whole lot more like you do now than you did when you used to.\n',
    '\nHis followers called him Mahasamatman and said he was a god.  He preferred\nto drop the Maha- and the -atman, however, and called himself Sam.  He never\nclaimed to be a god.  But then, he never claimed not to be a god.  Circum-\nstances being what they were, neither admission could be of any benefit.\nSilence, though, could.  It was in the days of the rains that their prayers\nwent up, not from the fingering of knotted prayer cords or the spinning of\nprayer wheels, but from the great pray-machine in the monastery of Ratri,\ngoddess of the Night.  The high-frequency prayers were directed upward through\nthe atmosphere and out beyond it, passing into that golden cloud called the\nBridge of the Gods, which circles the entire world, is seen as a bronze\nrainbow at night and is the place where the red sun becomes orange at midday.\nSome of the monks doubted the orthodoxy of this prayer technique...\n        -- Roger Zelazny, "Lord of Light"\n',
    '\nLay on, MacDuff, and curs\'d be him who first cries, "Hold, enough!".\n        -- Shakespeare\n',
    '\nPerfect day for scrubbing the floor and other exciting things.\n',
    '\nYou enjoy the company of other people.\n',
    '\nIf one cannot enjoy reading a book over and over again, there is no use\nin reading it at all.\n        -- Oscar Wilde\n',
    '\nYour  number is 3552664958674928.  Watch for it everywhere.\n',
    "\nThe mind is its own place, and in itself\nCan make a Heav'n of Hell, a Hell of Heav'n.\n        -- John Milton\n",
    "\nQ:How many hardware engineers does it take to change a light bulb?\nA:None.  We'll fix it in software.\n\nQ:How many system programmers does it take to change a light bulb?\nA:None.  The application can work around it.\n\nQ:How many software engineers does it take to change a light bulb?\nA:None.  We'll document it in the manual.\n\nQ:How many tech writers does it take to change a light bulb?\nA:None.  The user can figure it out.\n",
    '\nThe time is right to make new friends.\n',
    '\nAll things that are, are with more spirit chased than enjoyed.\n        -- Shakespeare, "Merchant of Venice"\n',
    '\nQ:How many journalists does it take to screw in a light bulb?\nA:Three.  One to report it as an inspired government program to bring\n    light to the people, one to report it as a diabolical government plot\n    to deprive the poor of darkness, and one to win a Pulitzer prize for\n    reporting that Electric Company hired a light bulb-assassin to break\n    the bulb in the first place.\n',
    '\nQ:How do you play religious roulette?\nA:You stand around in a circle and blaspheme and see who gets\n    struck by lightning first.\n',
    '\nBut, for my own part, it was Greek to me.\n        -- William Shakespeare, "Julius Caesar"\n',
    '\nThe true Southern watermelon is a boon apart, and not to be mentioned with\ncommoner things.  It is chief of the world\'s luxuries, king by the grace of God\nover all the fruits of the earth.  When one has tasted it, he knows what the\nangels eat.  It was not a Southern watermelon that Eve took; we know it because\nshe repented.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nYour own qualities will help prevent your advancement in the world.\n',
    '\nCourage is your greatest present need.\n',
    '\nYou will soon meet a person who will play an important role in your life.\n',
    '\nYour reasoning powers are good, and you are a fairly good planner.\n',
    '\nThere are more things in heaven and earth,\nHoratio, than are dreamt of in your philosophy.\n        -- Wm. Shakespeare, "Hamlet"\n',
    '\nLive in a world of your own, but always welcome visitors.\n',
    '\nThe very ink with which all history is written is merely fluid prejudice.\n        -- Mark Twain\n',
    '\nYou two ought to be more careful--your love could drag on for years and years.\n',
    '\nAlways do right.  This will gratify some people and astonish the rest.\n        -- Mark Twain\n',
    "\nQ:How many marketing people does it take to change a light bulb?\nA:I'll have to get back to you on that.\n",
    "\nI reverently believe that the maker who made us all  makes everything in New\nEngland, but the weather.  I don't know who makes that, but I think it must be\nraw apprentices in the weather-clerks factory who experiment and learn how, in\nNew England, for board and clothes, and then are promoted to make weather for\ncountries that require a good article, and will take their custom elsewhere\nif they don't get it.\n        -- Mark Twain\n",
    "\nDon't worry so loud, your roommate can't think.\n",
    '\nGood day to deal with people in high places; particularly lonely stewardesses.\n',
    '\nThe holy passion of Friendship is of so sweet and steady and loyal and\nenduring a nature that it will last through a whole lifetime, if not asked to\nlend money.\n        -- Mark Twain, "Pudd\'nhead Wilson\'s Calendar"\n',
    '\nYour love life will be... interesting.\n',
    '\n《赠阙下裴舍人》\n作者：钱起\n二月黄鹂飞上林，春城紫禁晓阴阴。\n长乐钟声花外尽，龙池柳色雨中深。\n阳和不散穷途恨，霄汉常悬捧日心。\n献赋十年犹未遇，羞将白发对华簪。\n',
    '\n《梦李白・其一》\n作者：杜甫\n死别已吞声，生别常恻恻。\n江南瘴疠地，逐客无消息。\n故人入我梦，明我常相忆。\n君今在罗网，何以有羽翼？\n恐非平生魂，路远不可测。\n魂来枫林青，魂返关塞黑。\n落月满屋梁，犹疑照颜色。\n水深波浪阔，无使蛟龙得。\n',
    '\n《塞下曲・其二》\n作者：王昌龄\n饮马渡秋水，水寒风似刀。\n平沙日未没，黯黯见临洮。\n昔日长城战，咸言意气高。\n黄尘足今古，白骨乱蓬蒿。\n',
    '\n《除夜有怀》\n作者：崔涂\n迢递三巴路，羁危万里身。\n乱山残雪夜，孤烛异乡人。\n渐与骨肉远，转于僮仆亲。\n那堪正漂泊，明日岁华新。\n',
    '\n《陇西行》\n作者：陈陶\n誓扫匈奴不顾身，五千貂锦丧胡尘。\n可怜无定河边骨，犹是深闺梦里人。\n',
    '\n《归嵩山作》\n作者：王维\n清川带长薄，车马去闲闲。\n流水如有意，暮禽相与还。\n荒城临古渡，落日满秋山。\n迢递嵩高下，归来且闭关。\n',
    '\n《宫词》\n作者：顾况\n玉楼天半起笙歌，风送宫嫔笑语和。\n月殿影开闻夜漏，水晶帘卷近秋河。\n',
    '\n《塞下曲・其二》\n作者：卢纶\n林暗草惊风，将军夜引弓。\n平明寻白羽，没在石棱中。\n',
    '\n《塞上》\n作者:柳开（９４６－９９９）\n鸣［骨交］直上一千尺，天静无风声更干。\n碧眼胡儿三百骑，尽提金勒向云看。\n',
    '\n《宿桐庐江寄广陵旧游》\n作者：孟浩然\n山暝听猿愁，沧江急夜流。\n风鸣两岸叶，月照一孤舟。\n建德非吾土，维扬忆旧游。\n还将两行泪，遥寄海西头。\n',
    '\n《无题・其一》\n作者：李商隐\n凤尾香罗薄几重，碧文圆顶夜深缝。\n扇裁月魄羞难掩，车走雷声语未通。\n曾是寂寥金烬暗，断无消息石榴红。\n斑骓只系垂杨岸，何处西南任好风。\n',
    '\n《金陵酒肆留别》\n作者：李白\n风吹柳花满店香，吴姬压酒唤客尝。\n金陵子弟来相送，欲行不行各尽觞。\n请君试问东流水，别意与之谁短长。\n',
    '\n《同题仙游观》\n作者：韩ꆼ\n仙台初见五城楼，风物凄凄宿雨收。\n山色遥连秦树晚，砧声近报汉宫秋。\n疏松影落空坛静，细草香闲小洞幽。\n何用别寻方外去，人间亦自有丹丘。\n',
    '\n《谷口书斋寄杨补阙》\n作者：钱起\n泉壑带茅茨，云霞生薜帷。\n竹怜新雨后，山爱夕阳时。\n闲鹭栖常早，秋花落更迟。\n家僮扫罗径，昨与故人期。\n',
    '\n《贼退示官吏・并序》\n作者：元结\n癸卯岁西原贼入道州，焚烧杀掠，几尽而去。\n明年，贼又攻永州破邵，不犯此州边鄙而退。\n岂力能制敌欤？盖蒙其伤怜而已。\n诸使何为忍苦征敛，故作诗一篇以示官吏。\n����\n昔岁逢太平，山林二十年。\n泉源在庭户，洞壑当门前。\n井税有常期，日晏犹得眠。\n忽然遭世变，数岁亲戎旃。\n今来典斯郡，山夷又纷然。\n城小贼不屠，人贫伤可怜。\n是以陷邻境，此州独见全。\n使臣将王命，岂不如贼焉。\n令彼征敛者，迫之如火煎。\n谁能绝人命，以作时世贤。\n思欲委符节，引竿自刺船。\n将家就鱼麦，归老江湖边。\n',
    '\n《遣怀》\n作者：杜牧\n落魄江湖载酒行，楚腰纤细掌中轻。\n十年一觉扬州梦，赢得青楼薄幸名。\n',
    '\n《送梓州李使君》\n作者：王维\n万壑树参天，千山响杜鹃。\n山中一夜雨，树杪百重泉。\n汉女输ꆼ布，巴人讼芋田。\n文翁翻教授，不敢倚先贤。\n',
    '\n《明妃曲》二首\n作者:王安石（１０２１－１０８６）\n\n            其一\n\n明妃初出汉宫时，泪湿春风鬓脚垂。\n低徊顾影无颜色，尚得君王不自持。\n归来却怪丹青手，入眼平生几曾有；\n意态由来画不成，当时枉杀毛延寿。\n一去心知更不归，可怜着尽汉宫衣；\n寄声欲问塞南事，只有年年鸿雁飞。\n家人万里传消息，好在毡城莫相忆；\n君不见咫尺长门闭阿娇，人生失意无南北。\n\n\n            其二\n\n明妃初嫁与胡儿，毡车百辆皆胡姬。\n含情欲语独无处，传与琵琶心自知。\n黄金杆拨春风手，弹看飞鸿劝胡酒。\n汉宫侍女暗垂泪，沙上行人却回首。\n汉恩自浅胡恩深，人生乐在相知心。\n可怜青冢已芜没，尚有哀弦留至今。\n',
    '\n《赠孟浩然》\n作者：李白\n吾爱孟夫子，风流天下闻。\n红颜弃轩冕，白首卧松云。\n醉月频中圣，迷花不事君。\n高山安可仰，徒此揖清芬。\n',
    '\n《过故人庄》\n作者：孟浩然\n故人具鸡黍，邀我至田家。\n绿树村边合，青山郭外斜。\n开轩面场圃，把酒话桑麻。\n待到重阳日，还来就菊花。\n',
    '\n《寓居吴兴》\n作者:曾几（１０８４－１１６６）\n相对真成泣楚囚，遂无末策到神州。\n但知绕树如飞鹊，不解营巢似拙鸠。\n江北江南犹断绝，秋风秋雨敢淹留？\n低回又作荆州梦，落日孤云始欲愁。\n',
    '\n《春日》\n作者:秦观（１０４９－１１００）\n一夕轻雷落万丝，霁光浮瓦碧参差。\n有情芍药含春泪，无力蔷薇卧晓枝。\n',
    '\n《惠崇春江晚景》\n作者:苏轼（１０３６－１１０１）\n竹外桃花三两枝，春江水暖鸭先知。\n萎蒿满地芦芽短，正是河豚欲上时。\n',
    '\n《闲居初夏午睡起》\n作者:杨万里（１１２７－１２０６）\n梅子留酸软齿牙，芭蕉分绿与窗纱。\n日长睡起无情思，闲看儿童捉柳花。\n',
    '\n《饯别王十一南游》\n作者：刘长卿\n望君烟水阔，浑手泪沾巾。\n飞鸟没何处，青山空向人。\n长江一帆远，落日五湖春。\n谁见汀洲上，相思愁白苹。\n',
    '\n《夏日南亭怀辛大》\n作者：孟浩然\n山光忽西落，池月渐东上。\n散发乘夕凉，开轩卧闲敞。\n荷风送香气，竹露滴清响。\n欲取鸣琴弹，恨无知音赏。\n感此怀故人，中宵劳梦想。\n',
    '\n《金缕衣》\n作者：杜秋娘\n劝君莫惜金缕衣，劝君惜取少年时。\n花开堪折直须折，莫待无花空折枝。\n',
    '\n《秋思》\n作者:陆游（１１２５－１２１０）\n利欲驱人万火牛，江湖浪迹一沙鸥。\n日长似岁闲方觉，事大如山醉亦休。\n衣杵相望深巷月，井桐摇落故园秋。\n欲舒老眼无高处，安得元龙百尺楼。\n',
    '\n《登高》\n作者：杜甫\n风急天高猿啸哀，渚清沙白鸟飞回。\n无边落木萧萧下，不尽长江滚滚来。\n万里悲秋常作客，百年多病独登台。\n艰难苦恨繁霜鬓，潦倒新停浊酒杯。\n',
    '\n《宣州谢ꆼ楼饯别校书叔云》\n作者：李白\n弃我去者，昨日之日不可留。\n乱我心者，今日之日多烦忧。\n长风万里送秋雁，对此可以酣高楼。\n蓬莱文章建安骨，中间小谢又清发。\n俱怀逸兴壮思飞，欲上青天览日月。\n抽刀断水水更流，举杯消愁愁更愁。\n人生在世不称意，明朝散发弄扁舟。\n',
    '\n《无题》\n作者：李商隐\n昨夜星辰昨夜风，画楼西畔桂堂东。\n身无彩凤双飞翼，心有灵犀一点通。\n隔座送钩春酒暖，分曹射覆蜡灯红。\n嗟余听鼓应官去，走马兰台类转蓬。\n',
    '\n《后宫词》\n作者：白居易\n泪湿罗巾梦不成，夜深前殿按歌声。\n红颜未老恩先断，斜倚熏笼坐到明。\n',
    '\n《寄李儋元锡》\n作者：韦应物\n去年花里逢君别，今日花开又一年。\n世事茫茫难自料，春愁黯黯独成眠。\n身多疾病思田里，邑有流亡愧俸钱。\n闻道欲来相问讯，西楼望月几回圆。\n',
    '\n《遣悲怀・其二》\n作者：元稹\n昔日戏言身后事，今朝都到眼前来。\n衣裳已施行看尽，针线犹存未忍开。\n尚想旧情怜婢仆，也曾因梦送钱财。\n诚知此恨人人有，贫贱夫妻百事哀。\n',
    '\n《溪居》\n作者：柳宗元\n久为簪组累，幸此南夷谪。\n闲依农圃邻，偶似山林客。\n晓耕翻露草，夜榜响溪石。\n来往不逢人，长歌楚天碧。\n',
    '\n《终南别业》\n作者：王维\n中岁颇好道，晚家南山陲。\n兴来每独往，胜事空自知。\n行到水穷处，坐看云起时。\n偶然值林叟，谈笑无还期。\n',
    '\n《孤山寺瑞上人房写望》\n作者:林逋（９６７－１０２８）\n底处凭栏思眇然，孤山塔后阁西偏。\n阴沉画轴林间寺，零落棋枰葑上田。\n秋景有时飞独鸟，夕阳无事起寒烟。\n迟留更爱吾庐近，只待春来看雪天。\n',
    '\n《长相思・其一》\n作者：李白\n长相思，在长安。\n络纬秋啼金井阑，微霜凄凄簟色寒。\n孤灯不明思欲绝，卷帷望月空长叹。\n美人如花隔云端，上有青冥之高天，下有渌水之波澜。\n天长地远魂飞苦，梦魂不到关山难。\n长相思，摧心肝。\n',
    '\n《已凉》\n作者：韩翎\n碧阑干外绣帘垂，猩色屏风画折枝。\n八尺龙须方锦褥，已凉天气未寒时。\n',
    '\n《酬程延秋夜即事见赠》\n作者：韩ꆼ\n长簟迎风早，空城澹月华。\n星河秋一雁，砧杵夜千家。\n节候看应晚，心期卧已赊。\n向来吟秀句，不觉已鸣鸦。\n',
    '\n《登乐游原》\n作者：李商隐\n向晚意不适，驱车登古原。\n夕阳无限好，只是近黄昏。\n',
    '\n《题大庾岭北驿》\n作者：宋之问\n阳月南飞雁，传闻至此回。\n我行殊未已，何日复归来。\n江静潮初落，林昏瘴不开，\n明朝望乡处，应见陇头梅。\n',
    '\n《送孟浩然之广陵》\n作者：李白\n故人西辞黄鹤楼，烟花三月下扬州。\n孤帆远影碧空尽，惟见长江天际流。\n',
    '\n《春晴怀故园海棠》\n作者:杨万里（１１２７－１２０６）\n竹边台榭水边亭，不要人随只独行。\n乍暖柳条无气力，淡晴花影不分明。\n一番过雨来幽径，无数新禽有喜声。\n只欠翠纱红映肉，两年寒食负先生。\n',
    '\n《石鼓歌》\n作者：韩愈\n张生手持石鼓文，劝我试作石鼓歌。\n少陵无人谪仙死，才薄将奈石鼓何。\n周纲凌迟四海沸，宣王愤起挥天戈。\n大开明堂受朝贺，诸侯剑佩鸣相磨。\n搜于岐阳骋雄俊，万里禽兽皆遮罗。\n镌功勒成告万世，凿石作鼓隳嵯峨。\n从臣才艺咸第一，拣选撰刻留山阿。\n雨淋日炙野火燎，鬼物守护烦[扌为]呵。\n公从何处得纸本，毫发尽备无差讹。\n辞严义密读难晓，字体不类隶与蝌。\n年深岂免有缺画，快剑砍断生蛟鼍。\n鸾翔凤翥众仙下，珊瑚碧树交枝柯。\n金绳铁索锁钮壮，古鼎跃水龙腾梭。\n陋儒编诗不收入，二雅褊迫无委蛇。\n孔子西行不到秦，掎摭星宿遗羲娥。\n嗟余好古生苦晚，对此涕泪双滂沱。\n忆昔初蒙博士征，其年始改称元和。\n古人从军在右辅，为我度量掘臼科。\n濯冠沐浴告祭酒，如此至宝存岂多。\n毡包席裹可立致，十鼓只载数骆驼。\n荐诸太庙比郜鼎，光价岂止百倍过。\n圣恩若许留太学，诸生讲解得切磋。\n观经鸿都尚填咽，坐见举国来奔波。\n剜苔剔藓露节角，安置妥帖平不颇。\n大厦深檐与覆盖，经历久远期无陀。\n中朝大官老于事，讵肯感激徒ꆼ婀。\n牧童敲火牛砺角，谁复著手为摩挲。\n日销月铄就埋没，六年西顾空吟哦。\n羲之俗书趁姿媚，数纸尚可博白鹅。\n继周八代争战罢，无人收拾理则那。\n方今太平日无事，柄任儒术崇丘轲。\n安能以此上论列，愿借辩口如悬河。\n石鼓之歌止于此，呜呼吾意其蹉跎。\n',
    '\n《泪》\n作者:杨亿（９６４－１０２０）\n锦字梭停掩夜机，白头吟若怨新知。\n谁闻陇水回肠后，更听巴猿拭袂时。\n汉殿微凉金屋闭，魏宫清晓玉壶欹。\n多情不待悲秋气，只是伤春鬓已丝。\n',
    '\n《九月九日忆山东兄弟》\n作者：王维\n独在异乡为异客，每逢佳节倍思亲。\n遥知兄弟登高处，遍插茱萸少一人。\n',
    '\n《秋日》\n作者:程颢（１０３２－１０８５）\n闲来无事不从容，睡觉东窗日已红。\n万物静观皆自得，四时佳兴与人同。\n道通天地有形外，思入风云变态中。\n富贵不淫贫贱乐，男儿到此是豪雄。\n',
    '\n《剑门道中遇微雨》\n作者:陆游（１１２５－１２１０）\n衣上征尘杂酒痕，远游无处不消魂。\n此身合是诗人未？细雨骑驴入剑门。\n',
    '\n《琵琶行・并序》\n作者：白居易\n元和十年，余左迁九江郡司马。明年秋，送客湓浦口，闻舟中夜弹琵琶者。\n听其音，铮铮然有京都声。问其人，本长安倡女，尝学琶琵于穆曹二善才。\n年长色衰，委身为贾人妇。遂令酒使快弹数曲。曲罢悯然，自叙少小时\n欢乐事，今漂沦憔悴，转徒于江湖间余出官二年，恬然自安，感斯人言，\n是夕始觉有迁谪意。因为长句歌以赠之，凡六百一十六言。命曰《琵琶行》。\n��\n浔阳江头夜送客，枫叶荻花秋瑟瑟。\n主人下马客在船，举酒欲饮无管弦。\n醉不成欢惨将别，别时茫茫江浸月。\n忽闻水上琵琶声，主人忘归客不发。\n寻声暗问弹者谁，琵琶声停欲语迟。\n移船相近邀相见，添酒回灯重开宴。\n千呼万唤始出来，犹抱琵琶半遮面。\n转轴拨弦三两声，未成曲调先有情。\n弦弦掩抑声声思，似诉平生不得志。\n低眉信手续续弹，说尽心中无限事。\n轻拢慢捻抹复挑，初为霓裳后六幺。\n大弦嘈嘈如急雨，小弦切切如私语。\n嘈嘈切切错杂弹，大珠小珠落玉盘。\n间关莺语花底滑，幽咽泉流水下滩。\n水泉冷涩弦凝绝，凝绝不通声渐歇。\n别有幽愁暗恨生，此时无声胜有声。\n银瓶乍破水浆迸，铁骑突出刀枪鸣。\n曲终收拨当心画，四弦一声如裂帛。\n东船西舫悄无言，唯见江心秋月白。\n沉吟放拨插弦中，整顿衣裳起敛容。\n自言本是京城女，家在虾蟆陵下住。\n十三学得琵琶成，名属教坊第一部。\n曲罢常教善才服，妆成每被秋娘炉。\n五陵年少争缠头，一曲红消不知数。\n钿头银篦击节碎，血色罗裙翻酒污。\n今年欢笑复明年，秋月春风等闲度。\n弟走从军阿姨死，暮去朝来颜色故。\n门前冷落车马稀，老大嫁作商人妇。\n商人重利轻别离，前月浮梁买茶去。\n去来江口守空船，绕舱明月江水寒。\n夜深忽梦少年事，梦啼妆泪红阑干。\n我闻琵琶已叹息，又闻此语重唧唧。\n同是天涯沦落人，相逢何必曾相识。\n我从去年辞帝京，谪居卧病浔阳城。\n浔阳地僻无音乐，终岁不闻丝竹声。\n住近湓江地低湿，黄芦苦竹绕宅生。\n其间旦暮闻何物，杜鹃啼血猿哀鸣。\n春江花朝秋月夜，往往取酒还独倾。\n岂无山歌与姑笛，呕哑嘲哳难为听。\n今夜闻君琵琶语，如听仙乐耳暂明。\n莫辞更坐弹一曲，为君翻作琵琶行。\n感我此言良久立，却坐促弦弦转急。\n凄凄不似向前声，满座重闻皆掩泣。\n座中泣下谁最多，江州司马清衫湿。\n',
    '\n《清平调・其三》\n作者：李白\n名花倾国两相欢，常得君王带笑看。\n解释春风无限恨，沉香亭北倚栏杆。\n',
    '\n《破山寺后禅院》\n作者：常建\n清晨入古寺，初日照高林。\n曲径通幽处，禅房花木深。\n山光悦鸟性，潭影空人心。\n万籁此俱寂，惟闻钟磬音。\n',
    '\n《喜见外弟卢纶见宿》\n作者：司空曙\n静夜四无邻，荒居旧业贫。\n雨中黄叶树，灯下白头人。\n以我独沉久，愧君相见频。\n平生自有分，况是霍家亲。\n',
    '\n《送陈章甫》\n作者：李颀\n四月南风大麦黄，枣花未落桐叶长。\n青山朝别暮还见，嘶马出门思旧乡。\n陈侯立身何坦荡，虬须虎眉仍大颡。\n腹中贮书一万卷，不肯低头在草莽。\n东门沽酒饮我曹，心轻万事皆鸿毛。\n醉卧不知白日暮，有时空望孤云高。\n长河浪头连天黑，津口停舟渡不得。\n郑国游人未及家，洛阳行子空叹息。\n闻道故林相识多，罢官昨日今如何。\n',
    '\n《长干行》\n作者：李白\n妾发初覆额，折花门前剧。\n郎骑竹马来，绕床弄青梅。\n同居长干里，两小无嫌猜。\n十四为君妇，羞颜未尝开。\n低头向暗壁，千唤不一回。\n十五始展眉，愿同尘与灰。\n常存抱柱信，岂上望夫台。\n十六君远行，瞿塘滟预堆。\n五月不可触，猿声天上哀。\n门前迟行迹，一一生绿苔。\n苔深不能扫，落叶秋风早。\n八月蝴蝶黄，双飞西园草。\n感此伤妾心，坐愁红颜老。\n早晚下三巴，预将书报家。\n相迎不道远，直至长风沙。\n',
    '\n《寻隐者不遇》\n作者：贾岛\n松下问童子，言师采药去。\n只在此山中，云深不知处。\n',
    '\n《将进酒》\n作者：李白\n君不见，黄河之水天上来，奔流到海不复回。\n君不见，高堂明镜悲白发，朝如青丝暮成雪。\n人生得意须尽欢，莫使金樽空对月。\n天生我材必有用，千金散尽还复来。\n烹羊宰牛且为乐，会须一饮三百杯。\n岑夫子，丹丘生，将进酒，君莫停。\n与君歌一曲，请君为我侧耳听。\n钟鼓馔玉不足贵，但愿长醉不愿醒。\n古来圣贤皆寂寞，惟有饮者留其名。\n陈王昔时宴平乐，斗酒十千恣欢谑。\n主人何为言少钱，径须沽取对君酌。\n五花马，千金裘，呼儿将出换美酒，\n与尔同销万古愁。\n',
    '\n《秋夜寄邱员外》\n作者：韦应物\n怀君属秋夜，散步咏凉天。\n空山松子落，幽人应未眠。\n',
    '\n《早秋》\n作者：许浑\n遥夜泛清瑟，西风生翠萝。\n残萤栖玉露，早雁拂金河。\n高树晓还密，远山晴更多。\n淮南一叶下，自觉洞庭波。\n',
    '\n《风雨》\n作者：李商隐\n凄凉宝剑篇，羁泊欲穷年。\n黄叶仍风雨，青楼自管弦。\n新知遭薄俗，旧好隔良缘。\n心断新丰酒，销愁又几千。\n',
    '\n《有美堂暴雨》\n作者:苏轼（１０３６－１１０１）\n游人脚底一声雷，满座顽云拨不开，\n天外黑风吹海立，浙东飞雨过江来。\n十分潋滟金樽凸，千杖敲铿羯鼓催。\n唤起谪仙泉酒面，倒倾鲛室泻琼瑰。\n',
    '\n《塞下曲・其三》\n作者：卢纶\n月黑雁飞高，单于夜遁逃。\n欲将轻骑逐，大雪满弓刀。\n',
    '\n《早发白帝城》\n作者：李白\n朝辞白帝彩云间，千里江陵一日还。\n两岸猿声啼不住，轻舟已过万重山。\n',
    '\n《自责》二首\n作者:朱淑真（《宋诗纪事》：“号幽栖居士，钱塘人，世居桃村。工诗，嫁为市井民妻，不得志殁。”）\n\n            其一\n\n女子弄文诚可罪，那堪咏月更吟风。\n磨穿铁砚非吾事，绣折金针却有功。\n\n\n            其二\n\n闷无消遣只看诗，不见诗中话别离。\n添得情怀转萧索，始知伶俐不如痴。\n',
    '\n《奉和圣制从蓬莱向兴庆阁道中留春雨中春望之作应制》\n作者：王维\n渭水自萦秦塞曲，黄山旧绕汉宫斜。\n銮舆迥出千门柳，阁道回看上苑花。\n云里帝城双凤阙，雨中春树万人家。\n为乘阳气行时令，不是宸游玩物华。\n',
    '\n《渡汉江》\n作者：李频\n岭外音书绝，经冬复立春。\n近乡情更怯，不敢问来人。\n',
    '\n《初入淮河》（选一）\n作者:杨万里（１１２７－１２０６）\n\n船离洪泽岸头沙，人到淮河意不佳。\n何必桑乾方是远，中流以北即天涯！\n',
    '\n《和子由踏青》\n作者:苏轼（１０３６－１１０１）\n春风陌上惊微尘，游人初乐岁华新。\n人闲正好路旁饮，麦短未怕游车轮。\n城中居人厌城郭，喧阗晓出空四邻。\n歌鼓惊山草木动，箪瓢散野乌鸢驯。\n何人聚众称道人，遮道卖符色怒嗔。\n宜蚕使汝茧如瓮，宜畜使汝羊如□［鹿下菌字去草头］。\n路人未必信此语，强为买符禳新春。\n道人得钱径沽酒，醉倒自谓吾符神。\n',
    '\n《九月登望仙台呈刘明府容》\n作者：崔曙\n汉文皇帝有高台，此日登临曙色开。\n三晋云山皆北向，二陵风雨自东来。\n关门令尹谁能识，河上仙翁去不回。\n且欲近寻彭泽宰，陶然共醉菊花杯。\n',
    '\n《嫦娥》\n作者：李商隐\n云母屏风烛影深，长河渐落晓星沉。\n嫦娥应悔偷灵药，碧海青天夜夜心。\n',
    '\n《旅夜书怀》\n作者：杜甫\n细草微风岸，危樯独夜舟。\n星垂平野阔，月涌大江流。\n名岂文章著，官应老病休，\n飘飘何所似，天地一沙鸥。\n',
    '\n《腊日游孤山访惠勤惠思二僧》\n作者:苏轼（１０３６－１１０１）\n天欲雪，云满湖，楼台明灭山有无。\n水清出石鱼可数，林深无人鸟相呼。\n腊日不归对妻孥，名寻道人实自娱。\n道人之居在何许？宝云山前路盘纡。\n孤山孤绝谁肯庐？道人有道山不孤。\n纸窗竹屋深自暖，拥褐坐睡依团蒲。\n天寒路远愁仆夫，整驾催归及未晡。\n出山回望云木合，但见野鹘盘浮图。\n兹游淡薄欢有余，到家恍如梦蘧蘧。\n作诗火急追亡逋，清景一失后难摹。\n',
    '\n《利州南渡》\n作者：温庭筠\n澹然空水对斜晖。曲岛苍茫接翠微。\n波上马嘶看棹去，柳边人歇待船归。\n数丛沙草群鸥散，万顷江田一鹭飞。\n谁解乘舟寻范蠡，五湖烟水独忘机。\n',
    '\n《江乡故人偶集客舍》\n作者：戴叔伦\n天秋月又满，城阙夜千重。\n还作江南会，翻疑梦里逢。\n风枝惊暗鹊，露草覆寒虫。\n羁旅长堪醉，相留畏晓钟。\n',
    '\n《游子吟》\n作者：孟郊\n慈母手中线，游子身上衣。\n临行密密缝，意恐迟迟归。\n谁言寸草心，报得三春晖。\n',
    '\n《燕歌行・并序》\n作者：高适\n开元二十六年，客有从元戎出塞而还者，作燕歌行以示适。\n感征戍之事，因而和焉。\n����\n汉家烟尘在东北，汉将辞家破残贼。\n男儿本自重横行，天子非常赐颜色。\n[扌从]金伐鼓下榆关，旌旗逶迤碣石间。\n校尉羽书飞瀚海，单于猎火照狼山。\n山川萧条极边土，胡骑凭陵杂风雨。\n战士军前半死生，美人帐下犹歌舞。\n大漠穷秋塞草腓，孤城落日斗兵稀。\n身当恩遇常轻敌，力尽关山未解围。\n铁衣远戍辛勤久，玉筋应啼别离后。\n少妇城南欲断肠，征人蓟北空回首。\n边风飘飘那可度，绝域苍茫更何有。\n杀气三时作阵云，寒声一夜传刁斗。\n相看白刃血纷纷，死节从来岂顾勋。\n君不见沙场征战苦，至今犹忆李将军。\n',
    '\n《晨诣超师院读禅经》\n作者：柳宗元\n汲井漱寒齿，清心拂尘服。\n闲持贝叶书，步出东斋读。\n真源了无取，妄迹世所逐。\n遗言冀可冥，缮性何由熟。\n道人庭宇静，苔色连深竹。\n日出雾露余，青松如膏沐。\n澹然离言说，悟悦心自足。\n',
    '\n《楚江怀古》\n作者：马戴\n露气寒光集，微阳下楚丘。\n猿啼洞庭树，人在木兰舟。\n广泽生明月，苍山夹乱流。\n云中君不见，竟夕自悲秋。\n',
    '\n《沈园》\n作者:陆游（１１２５－１２１０）\n城上斜阳画角哀，沈园非复旧池台，\n伤心桥下春波绿，曾是惊鸿照影来。\n\n梦断香消四十年，沈园柳老不吹绵。\n此身行作稽山土，犹吊遗踪一泫然。\n',
    '\n《春晓》\n作者：孟浩然\n春眠不觉晓，处处闻啼鸟。\n夜来风雨声，花落知多少。\n',
    '\n《望月怀远》\n作者：张九龄\n海上生明月，天涯共此时。\n情人怨遥夜，竟夕起相思。\n灭烛怜光满，披衣觉露滋。\n不堪盈手赠，还寝梦佳期。\n',
    '\n《过香积寺》\n作者：王维\n不知香积寺，数里入云峰。\n古木无人径，深山何处钟。\n泉声咽危石，日色冷青松。\n薄暮空潭曲，安禅制毒龙。\n',
    '\n《将赴吴兴登乐游原》\n作者：杜牧\n清时有味是无能，闲爱孤云静爱僧。\n欲把一麾江海去，乐游原上望昭陵。\n',
    '\n《在狱咏蝉・并序》\n作者：骆宾王\n余禁所禁垣西，是法厅事也，有古槐数株焉。\n虽生意可知，同殷仲文之古树；而听讼斯在，即周召伯之甘棠，\n每至夕照低阴，秋蝉疏引，发声幽息，有切尝闻，岂人心异于曩时，将虫响悲于前听？\n嗟乎，声以动容，德以象贤。\n故洁其身也，禀君子达人之高行；\n蜕其皮也，有仙都羽化之灵姿。\n候时而来，顺阴阳之数；\n应节为变，审藏用之机。\n有目斯开，不以道昏而昧其视；\n有翼自薄，不以俗厚而易其真。\n吟乔树之微风，韵姿天纵；\n饮高秋之坠露，清畏人知。\n仆失路艰虞，遭时徽ꆼ。\n不哀伤而自怨，未摇落而先衰。\n闻蟪蛄之流声，悟平反之已奏；\n见螳螂之抱影，怯危机之未安。\n感而缀诗，贻诸知己。\n庶情沿物应，哀弱羽之飘零；\n道寄人知，悯余声之寂寞。\n非谓文墨，取代幽忧云尔。\n���\n西陆蝉声唱，南冠客思深。\n不堪玄鬓影，来对白头吟。\n露重飞难进，风多响易沉。\n无人信高洁，谁为表予心。\n',
    '\n《章台夜思》\n作者：韦庄\n清瑟怨遥夜，绕弦风雨哀。\n孤灯闻楚角，残月下章台。\n芳草已云暮，故人殊未来。\n乡书不可寄，秋雁又南回。\n',
    '\n《送友人》\n作者：李白\n青山横北郭，白水绕东城。\n此地一为别，孤蓬万里征。\n浮云游子意，落日故人情。\n挥手自兹去，萧萧班马鸣。\n',
    '\n《野望》\n作者：杜甫\n西山白雪三城戍，南浦清江万里桥。\n海内风尘诸弟隔，天涯涕泪一身遥。\n惟将迟暮供多病，未有涓埃答圣朝。\n跨马出郊时极目，不堪人事日萧条。\n',
    '\n《草》\n作者：白居易\n离离原上草，一岁一枯荣。\n野火烧不尽，春风吹又生。\n远芳侵古道，晴翠接荒城。\n又送王孙去，萋萋满别情。\n',
    '\n《长干行・其一》\n作者：崔颢\n君家何处住，妾住在横塘。\n停船暂借问，或恐是同乡。\n',
    '\n苟利国家生死以，岂因祸福避趋之！\n',
    '\n《蜀先主庙》\n作者：刘禹锡\n天地英雄气，千秋尚凛然。\n势分三足鼎，业复五铢钱。\n得相能开国，生儿不象贤。\n凄凉蜀故妓，来舞魏宫前。\n'
]

emoji = [
    'o(￣▽￣)ｄ', '(>▽<)', '(≧∇≦)ﾉ', '<(￣︶￣)>', '╰(￣▽￣)╭',
    '(/≧▽≦)/', '(￣︶￣)↗', '(｡･∀･)ﾉﾞ', '（´v｀）', '(。・・)ノ',
    '￣O￣)ノ', '(－∀＝)', '(‾◡◝)', '(*￣ω￣)', '( *⊙~⊙)',
]


def get_fortune():
    select = random.randint(0, len(fortunes) - 1)
    return fortunes[select]


def get_emoji():
    select = random.randint(0, len(emoji) - 1)
    return ' ' + emoji[select]
